{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b01cbe4c-a3ab-44a1-8438-abf1f5548811",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Import needed libraries\n",
    "import streamlit as st\n",
    "import torchvision\n",
    "from medigan import Generators\n",
    "from torchvision.transforms.functional import to_pil_image\n",
    "from torchvision.utils import make_grid\n",
    "\n",
    "# Define the GAN models available in the app\n",
    "model_ids = [\n",
    "    \"00001\",\n",
    "    \"00002\",\n",
    "    \"00003\",\n",
    "    \"00004\",\n",
    "    \"00005\"\n",
    "]\n",
    "\n",
    "def main():\n",
    "    st.title(\"MEDIGAN Medical Image Data Generator\")\n",
    "\n",
    "    # Sidebar model selection\n",
    "    model_id = st.sidebar.selectbox(\"Select Model ID\", model_ids)\n",
    "\n",
    "    # Sidebar number input\n",
    "    num_images = st.sidebar.number_input(\n",
    "        \"Number of Images\",\n",
    "        min_value=1,\n",
    "        max_value=7,\n",
    "        value=1,\n",
    "        step=1\n",
    "    )\n",
    "\n",
    "    # Generate button\n",
    "    if st.sidebar.button(\"Generate Images\"):\n",
    "        generate_images(num_images, model_id)\n",
    "\n",
    "\n",
    "# -----------------------------\n",
    "# Torch image generation\n",
    "# -----------------------------\n",
    "def torch_images(num_images, model_id):\n",
    "    generators = Generators()\n",
    "\n",
    "    dataloader = generators.get_as_torch_dataloader(\n",
    "        model_id=model_id,\n",
    "        install_dependencies=True,\n",
    "        num_samples=num_images,\n",
    "        prefetch_factor=None,\n",
    "    )\n",
    "\n",
    "    images = []\n",
    "\n",
    "    for batch_idx, data_dict in enumerate(dataloader):\n",
    "        image_list = []\n",
    "\n",
    "        # SAMPLE\n",
    "        if \"sample\" in data_dict:\n",
    "            sample = data_dict[\"sample\"]\n",
    "\n",
    "            if sample.dim() == 4:\n",
    "                sample = sample.squeeze(0).permute(2, 0, 1)\n",
    "\n",
    "            sample = to_pil_image(sample).convert(\"RGB\")\n",
    "\n",
    "            transform = torchvision.transforms.Compose([\n",
    "                torchvision.transforms.ToTensor()\n",
    "            ])\n",
    "\n",
    "            sample = transform(sample)\n",
    "            image_list.append(sample)\n",
    "\n",
    "        # MASK\n",
    "        if \"mask\" in data_dict:\n",
    "            mask = data_dict[\"mask\"]\n",
    "\n",
    "            if mask.dim() == 4:\n",
    "                mask = mask.squeeze(0).permute(2, 0, 1)\n",
    "\n",
    "            mask = to_pil_image(mask).convert(\"RGB\")\n",
    "            mask = transform(mask)\n",
    "            image_list.append(mask)\n",
    "\n",
    "        # Create grid\n",
    "        Grid = make_grid(image_list, nrow=2)\n",
    "\n",
    "        # Fix shape issues\n",
    "        if Grid.dim() == 4:\n",
    "            Grid = Grid.squeeze(0)\n",
    "\n",
    "        if Grid.size(-1) == 1:\n",
    "            Grid = Grid.squeeze(-1)\n",
    "\n",
    "        # Convert to PIL\n",
    "        img = torchvision.transforms.ToPILImage()(Grid)\n",
    "        images.append(img)\n",
    "\n",
    "    return images\n",
    "\n",
    "\n",
    "# -----------------------------\n",
    "# Streamlit display function\n",
    "# -----------------------------\n",
    "def generate_images(num_images, model_id):\n",
    "    st.subheader(\"Generated Images:\")\n",
    "\n",
    "    images = torch_images(num_images, model_id)\n",
    "\n",
    "    for i, img in enumerate(images):\n",
    "        st.image(\n",
    "            img,\n",
    "            caption=f\"Generated Image {i+1} (Model ID: {model_id})\",\n",
    "            use_container_width=True\n",
    "        )\n",
    "\n",
    "\n",
    "# -----------------------------\n",
    "# Run App\n",
    "# -----------------------------\n",
    "if __name__ == \"__main__\":\n",
    "    main()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
